from __future__ import annotations

import dataclasses
import os
import stat
from pathlib import Path

import anyio
import pytest

from icm_harness.agents.codex_cli import RESULT_SCHEMA, CodexCLIStageAgent
from icm_harness.agents.dry_run import DryRunStageAgent
from icm_harness.agents.factory import make_stage_agent
from icm_harness.application import HarnessApplication
from icm_harness.config import AgentConfig, load_config, write_default_config
from icm_harness.kernel.contracts import TaskIntent, TaskProfile

# A fake `codex` binary. It ignores every CLI flag, reads the stage prompt from
# stdin, extracts the required artifact names the harness asked for, and emits a
# schema-valid structured result. This exercises the real subprocess/parse path
# without an authenticated Codex CLI.
FAKE_CODEX = """#!/usr/bin/env python3
import json, re, sys

prompt = sys.stdin.read()
match = re.search(r"Required artifact names: (.+)", prompt)
names = []
if match and match.group(1).strip() != "none":
    names = [n.strip() for n in match.group(1).split(",") if n.strip()]
artifacts = {}
for name in names:
    if name.endswith(".json"):
        artifacts[name] = json.dumps({"fake_codex": True, "artifact": name})
    else:
        artifacts[name] = "# " + name + "\\ngenerated by fake codex\\n"
print(json.dumps({
    "status": "pass",
    "summary": "fake codex completed",
    "artifacts": artifacts,
    "trigger_codes": [],
}))
"""

FAKE_CODEX_NONZERO = """#!/usr/bin/env python3
import sys
sys.stderr.write("boom: simulated agent failure\\n")
sys.exit(3)
"""

FAKE_CODEX_BAD_JSON = """#!/usr/bin/env python3
import sys
sys.stdin.read()
print("this is not json")
"""


def _write_executable(path: Path, body: str) -> Path:
    path.write_text(body, encoding="utf-8")
    path.chmod(path.stat().st_mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)
    return path


def _initialize(root: Path) -> None:
    (root / "0_Context_Wiki").mkdir(parents=True)
    (root / "2_Working_State").mkdir(parents=True)
    (root / "2_Working_State/CURRENT").write_text("NONE\n", encoding="utf-8")
    write_default_config(root / ".harness/config.toml")


def _in_place_config(root: Path):
    cfg = load_config(root)
    return dataclasses.replace(
        cfg, workspace=dataclasses.replace(cfg.workspace, strategy="in_place")
    )


def _build_profile(objective: str = "ship the feature") -> TaskProfile:
    return TaskProfile(
        objective,
        intent=TaskIntent.BUILD,
        specification_clarity=0.9,
        epistemic_uncertainty=0.1,
        stakes=0.4,
        reversibility=0.8,
        production_change_required=True,
    )


# --- factory dispatch -------------------------------------------------------


def test_factory_returns_dry_run_when_requested():
    assert isinstance(make_stage_agent(AgentConfig(), dry_run=True), DryRunStageAgent)


def test_factory_returns_dry_run_for_dry_run_provider():
    assert isinstance(make_stage_agent(AgentConfig(provider="dry-run")), DryRunStageAgent)


def test_factory_returns_codex_agent_for_codex_provider():
    agent = make_stage_agent(AgentConfig(provider="codex-cli", executable="codex"))
    assert isinstance(agent, CodexCLIStageAgent)
    assert agent.executable == "codex"


def test_factory_rejects_unknown_provider():
    with pytest.raises(ValueError, match="unsupported agent provider"):
        make_stage_agent(AgentConfig(provider="mystery"))


# --- CodexCLIStageAgent pure behaviour --------------------------------------


def test_available_reflects_executable_presence(tmp_path):
    fake = _write_executable(tmp_path / "codex", FAKE_CODEX)
    assert CodexCLIStageAgent(executable=str(fake)).available() is True
    assert CodexCLIStageAgent(executable=str(tmp_path / "missing")).available() is False


def test_schema_path_writes_expected_schema_and_is_idempotent(tmp_path):
    agent = CodexCLIStageAgent()
    path = agent._schema_path(tmp_path)
    assert path.exists()
    first = path.read_text(encoding="utf-8")
    assert '"status"' in first
    # required keys from the contract are present
    for key in RESULT_SCHEMA["required"]:
        assert key in first
    # A second call must not rewrite identical content (idempotent).
    mtime = path.stat().st_mtime_ns
    again = agent._schema_path(tmp_path)
    assert again.read_text(encoding="utf-8") == first
    assert again.stat().st_mtime_ns == mtime


def test_environment_filters_to_inherited_names(monkeypatch):
    monkeypatch.setenv("PATH", "/usr/bin")
    monkeypatch.setenv("CODEX_HOME", "/tmp/codex")
    monkeypatch.setenv("SECRET_TOKEN", "do-not-leak")
    agent = CodexCLIStageAgent(inherit_environment=("PATH", "CODEX_HOME"))
    env = agent._environment()
    assert env == {"PATH": "/usr/bin", "CODEX_HOME": "/tmp/codex"}
    assert "SECRET_TOKEN" not in env


# --- end-to-end through the application service ------------------------------


def test_real_agent_path_completes_a_build_round(tmp_path):
    _initialize(tmp_path)
    fake = _write_executable(tmp_path / "codex", FAKE_CODEX)
    app = HarnessApplication(
        tmp_path,
        config=_in_place_config(tmp_path),
        agent=CodexCLIStageAgent(executable=str(fake)),
    )
    created = app.create_round(_build_profile())
    result = anyio.run(app.run_round, created.round_id)

    assert result.status == "closed"
    names = [a.name for a in app.list_artifacts(result.round_id)]
    assert "execution-plan.md" in names
    assert "final-record.md" in names
    # The content came from the fake agent via the real subprocess path.
    _, content = app.read_artifact(
        next(a.id for a in app.list_artifacts(result.round_id) if a.name == "final-record.md")
    )
    assert "generated by fake codex" in content


def test_real_agent_failure_is_bounded_and_fails_closed(tmp_path):
    _initialize(tmp_path)
    fake = _write_executable(tmp_path / "codex", FAKE_CODEX_NONZERO)
    app = HarnessApplication(
        tmp_path,
        config=_in_place_config(tmp_path),
        agent=CodexCLIStageAgent(executable=str(fake)),
    )
    created = app.create_round(_build_profile())
    result = anyio.run(app.run_round, created.round_id)

    assert result.status == "failed"
    failures = [e for e in app.events(created.round_id) if e.kind == "stage_attempt_failed"]
    assert len(failures) == app.config.runtime.max_attempts
    assert "boom: simulated agent failure" in (result.last_error or "")


def test_real_agent_invalid_json_fails_closed(tmp_path):
    _initialize(tmp_path)
    fake = _write_executable(tmp_path / "codex", FAKE_CODEX_BAD_JSON)
    app = HarnessApplication(
        tmp_path,
        config=_in_place_config(tmp_path),
        agent=CodexCLIStageAgent(executable=str(fake)),
    )
    created = app.create_round(_build_profile())
    result = anyio.run(app.run_round, created.round_id)

    assert result.status == "failed"
    assert "invalid structured output" in (result.last_error or "")


def test_missing_executable_reports_a_clear_error(tmp_path):
    _initialize(tmp_path)
    app = HarnessApplication(
        tmp_path,
        config=_in_place_config(tmp_path),
        agent=CodexCLIStageAgent(executable=str(tmp_path / "nope")),
    )
    created = app.create_round(_build_profile())
    result = anyio.run(app.run_round, created.round_id)

    assert result.status == "failed"
    assert "agent executable not found" in (result.last_error or "")
    # Every failed attempt must have released its lease (regression guard).
    assert os.path.exists(tmp_path / ".harness")
