from __future__ import annotations

import dataclasses
import json
import os
import stat
from pathlib import Path

import anyio
import pytest

from icm_harness.agents.claude_cli import ClaudeCLIStageAgent
from icm_harness.agents.dry_run import DryRunStageAgent
from icm_harness.agents.factory import make_stage_agent
from icm_harness.application import HarnessApplication
from icm_harness.config import AgentConfig, load_config, write_default_config
from icm_harness.kernel.contracts import TaskIntent, TaskProfile

# A fake `claude` binary. It ignores every CLI flag, reads the stage prompt from
# stdin, extracts the artifact names the harness asked for, and emits a
# `claude -p --output-format json` ENVELOPE whose `result` field carries the
# stage-contract JSON as a string — exactly the shape the real CLI produces.
# This exercises the real subprocess + envelope-unwrap + parse path without an
# authenticated Claude CLI.
FAKE_CLAUDE = """#!/usr/bin/env python3
import json, re, sys

prompt = sys.stdin.read()
match = re.search(r"Required artifact names: (.+)", prompt)
names = []
if match and match.group(1).strip() != "none":
    names = [n.strip() for n in match.group(1).split(",") if n.strip()]
artifacts = {}
for name in names:
    if name.endswith(".json"):
        artifacts[name] = json.dumps({"fake_claude": True, "artifact": name})
    else:
        artifacts[name] = "# " + name + "\\ngenerated by fake claude\\n"
stage_result = json.dumps({
    "status": "pass",
    "summary": "fake claude completed",
    "artifacts": artifacts,
    "trigger_codes": [],
})
print(json.dumps({
    "type": "result",
    "subtype": "success",
    "is_error": False,
    "result": stage_result,
    "session_id": "fake",
    "total_cost_usd": 0.0,
}))
"""

# Same, but wraps the stage JSON in a Markdown code fence inside `result` — the
# common model slip the adapter must salvage.
FAKE_CLAUDE_FENCED = """#!/usr/bin/env python3
import json, re, sys

prompt = sys.stdin.read()
match = re.search(r"Required artifact names: (.+)", prompt)
names = []
if match and match.group(1).strip() != "none":
    names = [n.strip() for n in match.group(1).split(",") if n.strip()]
artifacts = {}
for n in names:
    if n.endswith(".json"):
        artifacts[n] = json.dumps({"fake_claude": True, "artifact": n})
    else:
        artifacts[n] = "# " + n + "\\nfenced\\n"
stage_result = json.dumps({
    "status": "pass", "summary": "fenced", "artifacts": artifacts, "trigger_codes": [],
})
print(json.dumps({
    "type": "result", "subtype": "success", "is_error": False,
    "result": "```json\\n" + stage_result + "\\n```",
}))
"""

# The CLI itself reports an error (auth failure, etc.): envelope is_error=true.
FAKE_CLAUDE_ERROR_ENVELOPE = """#!/usr/bin/env python3
import json, sys
sys.stdin.read()
print(json.dumps({
    "type": "result", "subtype": "error_during_execution", "is_error": True,
    "result": "simulated claude auth failure",
}))
"""

# Non-zero exit with a message on stderr.
FAKE_CLAUDE_NONZERO = """#!/usr/bin/env python3
import sys
sys.stderr.write("boom: simulated claude crash\\n")
sys.exit(2)
"""

# Valid envelope, but `result` is not JSON — off-contract model output.
FAKE_CLAUDE_BAD_STAGE_JSON = """#!/usr/bin/env python3
import json, sys
sys.stdin.read()
print(json.dumps({
    "type": "result", "subtype": "success", "is_error": False,
    "result": "I could not follow the schema, sorry.",
}))
"""

# Records the argv it was invoked with so a test can assert the read-only
# stage denied the write tools.
FAKE_CLAUDE_ARGV_ECHO = """#!/usr/bin/env python3
import json, sys
sys.stdin.read()
print(json.dumps({
    "type": "result", "subtype": "success", "is_error": False,
    "result": json.dumps({"status": "pass", "summary": " ".join(sys.argv[1:]),
                          "artifacts": {}, "trigger_codes": []}),
}))
"""


def _write_executable(path: Path, body: str) -> Path:
    path.write_text(body, encoding="utf-8")
    path.chmod(path.stat().st_mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)
    return path


def _initialize(root: Path) -> None:
    (root / "0_Context_Wiki").mkdir(parents=True)
    (root / "2_Working_State").mkdir(parents=True)
    (root / "2_Working_State/CURRENT").write_text("NONE\n", encoding="utf-8")
    write_default_config(root / ".harness/config.toml")


def _in_place_config(root: Path):
    cfg = load_config(root)
    return dataclasses.replace(
        cfg, workspace=dataclasses.replace(cfg.workspace, strategy="in_place")
    )


def _build_profile(objective: str = "ship the feature") -> TaskProfile:
    return TaskProfile(
        objective,
        intent=TaskIntent.BUILD,
        specification_clarity=0.9,
        epistemic_uncertainty=0.1,
        stakes=0.4,
        reversibility=0.8,
        production_change_required=True,
    )


# --- factory dispatch -------------------------------------------------------


def test_factory_returns_claude_agent_for_claude_provider():
    agent = make_stage_agent(AgentConfig(provider="claude-cli", executable="claude"))
    assert isinstance(agent, ClaudeCLIStageAgent)
    assert agent.executable == "claude"


def test_factory_still_returns_dry_run_when_requested():
    assert isinstance(
        make_stage_agent(AgentConfig(provider="claude-cli"), dry_run=True), DryRunStageAgent
    )


# --- pure behaviour ---------------------------------------------------------


def test_available_reflects_executable_presence(tmp_path):
    fake = _write_executable(tmp_path / "claude", FAKE_CLAUDE)
    assert ClaudeCLIStageAgent(executable=str(fake)).available() is True
    assert ClaudeCLIStageAgent(executable=str(tmp_path / "missing")).available() is False


def test_environment_forwards_auth_env_plus_inherited(monkeypatch):
    monkeypatch.setenv("PATH", "/usr/bin")
    monkeypatch.setenv("ANTHROPIC_BASE_URL", "https://example.invalid")
    monkeypatch.setenv("ANTHROPIC_API_KEY", "sk-test")
    monkeypatch.setenv("SECRET_TOKEN", "do-not-leak")
    agent = ClaudeCLIStageAgent(inherit_environment=("PATH",))
    env = agent._environment()
    assert env["PATH"] == "/usr/bin"
    # Anthropic auth env is forwarded even though it is not in inherit_environment.
    assert env["ANTHROPIC_BASE_URL"] == "https://example.invalid"
    assert env["ANTHROPIC_API_KEY"] == "sk-test"
    # Anything outside inherit_environment + the auth allowlist is filtered.
    assert "SECRET_TOKEN" not in env


def test_extract_stage_json_strips_fence_and_prose():
    agent = ClaudeCLIStageAgent()
    obj = '{"status": "pass"}'
    assert json.loads(agent._extract_stage_json(obj)) == {"status": "pass"}
    assert json.loads(agent._extract_stage_json("```json\n" + obj + "\n```")) == {"status": "pass"}
    assert json.loads(agent._extract_stage_json("here you go:\n" + obj)) == {"status": "pass"}


def test_unwrap_envelope_raises_on_cli_error():
    from icm_harness.agents.errors import StageAgentError

    agent = ClaudeCLIStageAgent()
    with pytest.raises(StageAgentError, match="claude CLI reported an error"):
        agent._unwrap_envelope(json.dumps({"is_error": True, "result": "nope"}))


# --- end-to-end through the application service ------------------------------


def test_real_agent_path_completes_a_build_round(tmp_path):
    _initialize(tmp_path)
    fake = _write_executable(tmp_path / "claude", FAKE_CLAUDE)
    app = HarnessApplication(
        tmp_path,
        config=_in_place_config(tmp_path),
        agent=ClaudeCLIStageAgent(executable=str(fake)),
    )
    created = app.create_round(_build_profile())
    result = anyio.run(app.run_round, created.round_id)

    assert result.status == "closed"
    names = [a.name for a in app.list_artifacts(result.round_id)]
    assert "execution-plan.md" in names
    assert "final-record.md" in names
    _, content = app.read_artifact(
        next(a.id for a in app.list_artifacts(result.round_id) if a.name == "final-record.md")
    )
    assert "generated by fake claude" in content


def test_fenced_result_is_salvaged(tmp_path):
    _initialize(tmp_path)
    fake = _write_executable(tmp_path / "claude", FAKE_CLAUDE_FENCED)
    app = HarnessApplication(
        tmp_path,
        config=_in_place_config(tmp_path),
        agent=ClaudeCLIStageAgent(executable=str(fake)),
    )
    created = app.create_round(_build_profile())
    result = anyio.run(app.run_round, created.round_id)
    assert result.status == "closed"


def test_error_envelope_fails_closed(tmp_path):
    _initialize(tmp_path)
    fake = _write_executable(tmp_path / "claude", FAKE_CLAUDE_ERROR_ENVELOPE)
    app = HarnessApplication(
        tmp_path,
        config=_in_place_config(tmp_path),
        agent=ClaudeCLIStageAgent(executable=str(fake)),
    )
    created = app.create_round(_build_profile())
    result = anyio.run(app.run_round, created.round_id)
    assert result.status == "failed"
    assert "simulated claude auth failure" in (result.last_error or "")


def test_nonzero_exit_is_bounded_and_fails_closed(tmp_path):
    _initialize(tmp_path)
    fake = _write_executable(tmp_path / "claude", FAKE_CLAUDE_NONZERO)
    app = HarnessApplication(
        tmp_path,
        config=_in_place_config(tmp_path),
        agent=ClaudeCLIStageAgent(executable=str(fake)),
    )
    created = app.create_round(_build_profile())
    result = anyio.run(app.run_round, created.round_id)
    assert result.status == "failed"
    failures = [e for e in app.events(created.round_id) if e.kind == "stage_attempt_failed"]
    assert len(failures) == app.config.runtime.max_attempts
    assert "boom: simulated claude crash" in (result.last_error or "")


def test_offcontract_result_fails_closed(tmp_path):
    _initialize(tmp_path)
    fake = _write_executable(tmp_path / "claude", FAKE_CLAUDE_BAD_STAGE_JSON)
    app = HarnessApplication(
        tmp_path,
        config=_in_place_config(tmp_path),
        agent=ClaudeCLIStageAgent(executable=str(fake)),
    )
    created = app.create_round(_build_profile())
    result = anyio.run(app.run_round, created.round_id)
    assert result.status == "failed"
    assert "invalid structured output" in (result.last_error or "")


def test_missing_executable_reports_a_clear_error(tmp_path):
    _initialize(tmp_path)
    app = HarnessApplication(
        tmp_path,
        config=_in_place_config(tmp_path),
        agent=ClaudeCLIStageAgent(executable=str(tmp_path / "nope")),
    )
    created = app.create_round(_build_profile())
    result = anyio.run(app.run_round, created.round_id)
    assert result.status == "failed"
    assert "agent executable not found" in (result.last_error or "")
    assert os.path.exists(tmp_path / ".harness")


def test_readonly_stage_denies_write_tools(tmp_path):
    """A non-mutating stage must invoke claude with --disallowed-tools; a
    mutating one must not."""
    from icm_harness.agents.contracts import StageInvocation
    from icm_harness.kernel.contracts import ContextBundle, Mode, StageSpec

    agent = ClaudeCLIStageAgent(executable="claude")

    def _command_for(mutates: bool) -> list[str]:
        stage = StageSpec(mode=Mode.QUICK, name="y", mutates_workspace=mutates)
        inv = StageInvocation(
            round_id="r", profile=_build_profile(), stage=stage,
            context=ContextBundle(items=(), tier=0, used_tokens=0, budget_tokens=1),
            settings=None, workspace=tmp_path, artifact_dir=tmp_path,
            model="default", attempt=1, authorization=None, cancel_requested=lambda: False,
        )
        return agent._command(inv)

    read_only = _command_for(False)
    assert "--disallowed-tools" in read_only
    for tool in ("Edit", "Write", "MultiEdit", "NotebookEdit"):
        assert tool in read_only

    mutating = _command_for(True)
    assert "--disallowed-tools" not in mutating
