from typing import Any, Protocol


class DurableExecutor(Protocol):
    async def submit(self, workflow: str, payload: dict[str, Any]) -> str: ...
    async def cancel(self, run_id: str) -> None: ...
    async def status(self, run_id: str) -> str: ...
